image: node:boron

pipelines:
    default:
        - step:
            script:
                - npm set loglevel silent
                - npm set spin false
                - npm install
                - SAUCE_LABS=true SAUCE_USERNAME=$SAUCE_USERNAME SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY npm test
