image: node:boron

pipelines:
    branches:
      master:
        - step:
            script:
              - mkdir /temp
              - cd /temp
              - npm install npm@5
              - rm -rf /usr/local/lib/node_modules
              - mv node_modules /usr/local/lib/
              - cd $BITBUCKET_CLONE_DIR
              - npm set @atlassian:registry "https://npm-private-proxy.atlassian.io/"
              - npm set //npm-private-proxy.atlassian.io/:_authToken=$NPM_TOKEN
              - npm set loglevel silent
              - npm set spin false
              - TOKEN=`curl -s -S -f -X POST -u "${KEY}:${SECRET}" https://bitbucket.org/site/oauth2/access_token -d grant_type=client_credentials | python -c "import sys, json; print json.load(sys.stdin)['access_token']"`
              - git remote set-url origin https://x-token-auth:${TOKEN}@bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}.git
              - git config user.email "cwhittington@atlassian.com"
              - git config user.name "Build bot"
              - npm run release
              - node node_modules/gulp/bin/gulp.js
              - PACKAGE_VERSION=$(node -p "require('./package.json').version") && git add . && git commit -m "$PACKAGE_VERSION release [skip ci]"
              - git push origin master
              - npm run tag

    default:
        - step:
            script:
                - npm set loglevel silent
                - npm set spin false
                - npm set @atlassian:registry "https://npm-private-proxy.atlassian.io/"
                - npm set //npm-private-proxy.atlassian.io/:_authToken=$NPM_TOKEN
                - npm install
                - SAUCE_LABS=true SAUCE_USERNAME=$SAUCE_USERNAME SAUCE_ACCESS_KEY=$SAUCE_ACCESS_KEY npm test
