image: node:argon

pipelines:
    default:
        - step:
            script:
                - npm set //npm-private.atlassian.io/:_authToken $NPM_TOKEN
                - npm config set @atlassian:registry https://npm-private.atlassian.io
                - npm config set loglevel silent
                - npm install
                - npm test
